import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slim Shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Adidas fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '../images/p2.jpg',
    price: 90,
    countInStock: 6,
    brand: 'Adidas',
    rating: 4.8,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Lacoste free Pants',
    slug: 'lacoste-free-pants',
    category: 'Pants',
    image: '../images/p3.jpg',
    price: 601,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 3.3,
    numReviews: 1,
    description: 'Pants to a teenager is +600',
  },
  {
    name: 'Nike free Pants',
    slug: 'nike-free-pants',
    category: 'Pants',
    image: '../images/p4.jpg',
    price: 120,
    countInStock: 23,
    brand: 'Nike',
    rating: 4.0,
    numReviews: 12,
    description: 'Best pants in the market',
  },
]
